// import { Inter } from "next/font/google";

import { Sora } from "next/font/google";

import "./globals.css";
import "./output.css";

import Navbar from "@/components/Navbar";

import { cookies } from 'next/headers'


// const inter = Inter({ subsets: ["latin"] });
const sora = Sora({ subsets: ["latin"] });

export const metadata = {
  title: "Cine Rental | Learn with Sumit",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  const cookieStore = cookies()
  const theme = cookieStore?.get('theme') ? cookieStore.get('theme') : 'dark';

  return (
    <html lang="en" className={theme}>


      <body className={`dark:bg-body bg-white font-[Sora] dark:text-white text-dark ${sora.className}`}>
        <div id="modal-root" />

        <Navbar />

        {/* <!-- Begin Main --> */}
        <main>

          {children}

        </main>
      </body>
    </html>
  );
}
